services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      gitea_instance_base_url: ${GITEA_INSTANCE_BASE_URL}
      gitea_access_token: ${GITEA_ACCESS_TOKEN}
      gitea_owner: ${GITEA_OWNER}
      gitea_repository: ${GITEA_REPOSITORY}
      gitea_package_registry: ${GITEA_PACKAGE_REGISTRY}
    volumes:
      - ./src:/var/src
    networks:
      - bridge
networks:
  bridge:
    driver: bridge