version: "3"
services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      GITEA_INSTANCE_BASE_URL: ${GITEA_INSTANCE_BASE_URL}
      GITEA_ACCESS_TOKEN: ${GITEA_ACCESS_TOKEN}
      GITEA_OWNER: ${GITEA_OWNER}
      GITEA_REPOSITORY: ${GITEA_REPOSITORY}
      GITEA_PACKAGE_REGISTRY: ${GITEA_PACKAGE_REGISTRY}
    volumes:
      - ./src:/var/src
    networks:
      - bridge
networks:
  bridge:
    driver: bridge